### ISSUE TITLE
Button to add to homescreen appears to be missing on the landing page

### ISSUE THREAD

**Issue by AHelms** [fulcrumapp/fulcrum-homescreen#1]
On both iOS and Android (tested Safari and Chrome) there does not seem to be a way to add the widget to the home screen.

![image from ios 4](https://user-images.githubusercontent.com/1839844/47518080-f345ea80-d857-11e8-8731-394948678605.png)

**Comment by bmcbride** [comment]
@AHelms I think this functionality has been superseded by mobile widgets: https://www.fulcrumapp.com/blog/mobile-widgets/.

**Comment by AHelms** [comment]
I think mobile widgets is close but not the exact same, at least, for iOS. There is no way to add the widget to the home screen, but more importantly, the mobile widgets only display the recently used apps and there is no way to set which once show in the Today Widget.

**Comment by bmcbride** [comment]
@AHelms it actually works in Safari on iOS- you just have to manually add it to the homescreen by tapping the browser action button with the arrow and tapping the "Add to Home Screen" button. It doesn't appear to be working on Chrome due to some new security restrictions, but Android already has this built into the native app now.

**Comment by AHelms** [comment]
Sounds good, I will update the docs.
